In [1]:
import pandas as pd
df = pd.DataFrame([['green', 'M', 10.1, 'class1'],['red', 'L', 13.5, 'class2'],['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']

In [11]:
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [4]:
size_mapping = { 'XL' : 2, 'L' : 1 , 'M' :0}

In [5]:
df['size'] = df['size'].map(size_mapping)

In [8]:
inv_size_mapping = { v: k for k,v in size_mapping.items()}

In [10]:
df['size'] = df['size'].map(inv_size_mapping)

In [13]:
import numpy as np


In [14]:
class_mapping = { label : idx for idx, label in enumerate(np.unique(df['classlabel']))}

In [15]:
class_mapping

{'class1': 0, 'class2': 1}

In [19]:
inv_class_mapping = {v: k for k, v in class_mapping.items()}

In [20]:
df['classlabel'] = df['classlabel'].map(inv_class_mapping)

In [32]:
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [18]:
from sklearn.preprocessing import LabelEncoder

In [25]:
class_le = LabelEncoder()

In [26]:
y = class_le.fit_transform(df['classlabel'].values)

In [27]:
y

array([0, 1, 0], dtype=int64)

In [28]:
class_le.inverse_transform(y)

array(['class1', 'class2', 'class1'], dtype=object)

In [31]:
df['classlabel'] = class_le.inverse_transform(y)

In [33]:
X = df[['color', 'size', 'price']].values

In [46]:
color_le = LabelEncoder()
X[:,1] = class_le.fit_transform(X[:,1] )

In [47]:
X[:,1]

array([1, 0, 2], dtype=object)

In [48]:
X

array([[1, 1, 10.1],
       [2, 0, 13.5],
       [0, 2, 15.3]], dtype=object)

In [49]:
from sklearn.preprocessing import OneHotEncoder

In [58]:
ohe = OneHotEncoder(categorical_features='all')

In [59]:
ohe.fit_transform(X).toarray()[:,1:]

array([[1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1.]])

In [57]:
pd.get_dummies(df[['price', 'color', 'size']] , drop_first=True)

price  color_green  color_red  size_M  size_XL
0   10.1            1          0       1        0
1   13.5            0          1       0        0
2   15.3            0          0       0        1

In [60]:
from sklearn import datasets

In [61]:
wine = datasets.load_wine()

In [63]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [64]:
df_wine = pd.DataFrame(wine.data , columns=wine.feature_names)

In [65]:
df_wine.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [71]:
wine.target.shape

(178,)

In [77]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [73]:
df_wine.shape

(178, 13)

In [74]:
df_wine['class_label'] = wine.target

In [76]:
df_wine.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  class_label  
0                          3.92   1065.0            0  
1                          3.40   1050.0            0  
2                          3.17   1185.0            0  
3                          3.45   1480.0            0  
4                          2.93    735.0            0

In [81]:
X = df_wine.iloc[:,0:-1]