In [40]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectFromModel
from sklearn.decomposition import PCA
from sklearn.decomposition import KernelPCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [2]:
wine = datasets.load_wine()
df_wine = pd.DataFrame(wine.data , columns=wine.feature_names)
df_wine['class_label'] = wine.target
x = df_wine.iloc[:,0:-1].values
y = df_wine.iloc[:,-1].values
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size=0.3, random_state=1 , stratify = y)

In [4]:
pca1 = PCA(n_components=None)

In [29]:
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

In [6]:
pca1.fit(x_train_std)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [7]:
pca1.explained_variance_

array([4.7095539 , 2.63606471, 1.55728758, 0.93422662, 0.85129454,
       0.5709688 , 0.46462025, 0.37764772, 0.27571434, 0.2630501 ,
       0.21165109, 0.14951983, 0.10409155])

In [8]:
pca1.explained_variance_ratio_

array([0.35935182, 0.20113893, 0.11882529, 0.07128404, 0.0649561 ,
       0.04356648, 0.03545179, 0.02881555, 0.02103776, 0.02007144,
       0.01614956, 0.01140877, 0.00794247])

In [24]:
lda1 = LDA(n_components=2)

In [25]:
lda1.fit(x_train_std, y_train)

LinearDiscriminantAnalysis(n_components=2, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [26]:
lda1.classes_

array([0, 1, 2])

In [27]:
lda1.means_

array([[ 0.89976216, -0.35996329,  0.30103147, -0.74304582,  0.46792414,
         0.91761752,  0.98085519, -0.6287134 ,  0.64032575,  0.20178957,
         0.49581041,  0.76416637,  1.16973167],
       [-0.91914645, -0.36134188, -0.36704181,  0.29261151, -0.43620895,
        -0.11871457,  0.00975796,  0.10976533, -0.02351051, -0.85559328,
         0.37199541,  0.23427044, -0.76986063],
       [ 0.27475981,  0.99471481,  0.18211516,  0.47982737,  0.07956236,
        -0.9601997 , -1.23342305,  0.61481767, -0.75993424,  1.04564521,
        -1.17963629, -1.30437403, -0.28684748]])

In [30]:
lda1.score(x_test_std, y_test)

0.9814814814814815

In [37]:
lr1 = LogisticRegression(penalty='l1',  C=0.1,random_state= 1)

In [38]:
lr1.fit(x_train_std,y_train)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=1, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [39]:
lr1.score(x_test_std, y_test)

1.0

In [ ]:
kpca = KernelPCA()